[template]
engine = "handlebars"

[[template.templates]]
name = "auth-code.get"
path = "eddist-server/resources/templates/auth-code.get.hbs"

[[template.templates]]
name = "auth-code.post.success"
path = "eddist-server/resources/templates/auth-code.post.success.hbs"

[[template.templates]]
name = "auth-code.post.failed"
path = "eddist-server/resources/templates/auth-code.post.failed.hbs"

[[template.templates]]
name = "setting-txt.get"
path = "eddist-server/resources/templates/setting-txt.get.hbs"

[[template.templates]]
name = "user-reg-temp-url.get"
path = "eddist-server/resources/templates/user-reg-temp-url.get.hbs"

[[template.templates]]
name = "user-page-simple.get"
path = "eddist-server/resources/templates/user-page-simple.get.hbs"

[[template.templates]]
name = "login-idp-selection.get"
path = "eddist-server/resources/templates/login-idp-selection.get.hbs"

[[template.templates]]
name = "user-link-idp-selection.get"
path = "eddist-server/resources/templates/user-link-idp-selection.get.hbs"

[[template.templates]]
name = "error-page.get"
path = "eddist-server/resources/templates/error-page.get.hbs"
